let a = "hello"
try {
    let no = parseInt(aa)

} catch (e){
    console.log("error occured")
    console.log(e.name)
}