let a = 1
try {
    a.toPrecision(450)
    let no = parseInt(aa)

} catch (e){
    console.log("error occured")
    console.log(e.name)
}